function(add_sample_with_shared_lib_as_test Sample)
	if (BUILD_ALL OR BUILD_TESTS)
		if (ANDROID AND DEFINED ADBRUNNER)
			 set(SO_5_TEST_LAUNCHER ${ADBRUNNER})
			 list(APPEND SO_5_TEST_LAUNCHER -L$<TARGET_FILE_DIR:${SO_5_SHARED_LIB}>)
		endif()
		add_test(NAME ${Sample} COMMAND ${SO_5_TEST_LAUNCHER} ${Sample})
	endif()
endfunction()

function(add_sample_with_static_lib_as_test Sample)
	if (BUILD_ALL OR BUILD_TESTS)
		if (ANDROID AND DEFINED ADBRUNNER)
			 set(SO_5_TEST_LAUNCHER ${ADBRUNNER})
		endif()
		add_test(NAME ${Sample} COMMAND ${SO_5_TEST_LAUNCHER} ${Sample})
	endif()
endfunction()

